"""
export_static.py — bake a project's published player page into a static folder.

The player (`web/graph/play.html`) only ever *reads* from the backend: graph.json,
the shader/mathnode manifests, the gallery, and the images. So a project can be
frozen into a directory of plain files and dropped on any static host — no Python,
no ComfyUI, no writable disk.

    python export_static.py                        # current project -> dist/
    python export_static.py --project qri9         # a specific one
    python export_static.py --out build --all-images
    python export_static.py --list                 # what can be exported

Then serve the folder at a domain ROOT (Cloudflare Pages, Netlify, a bucket):

    cd dist && python -m http.server 8000

What survives the export: every shader and math node (pure client-side WebGL2),
the whole graph, the authored end-user UI, and the images it references. What does
not: saving (the page is read-only by design), image import, depth generation, and
AI Generate — all of those need the live backend, so their buttons no-op. AI nodes
still load and show their last cached output so the graph keeps its shape.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Set

from forge_server import config, projects, workflows

ROOT = config.ROOT
IMG_EXTS = (".png", ".jpg", ".jpeg", ".webp", ".bmp")

# API routes the player hits, mapped to the file we bake them into. Anything not
# listed here answers `{}` (GET) or `{"ok": true}` (write) from the shim.
ROUTE_FILES = {
    "/api/graph": "graph.json",
    "/api/shaders": "shaders.json",
    "/api/mathnodes": "mathnodes.json",
    "/api/gallery": "gallery.json",
    "/api/workflows": "workflows.json",
    "/api/projects": "projects.json",
    "/api/project": "project.json",
    "/api/settings": "settings.json",
    "/api/comfy/status": "comfy.json",
}


# ── the fetch shim ───────────────────────────────────────────────────────────
# A classic script that runs before the module graph boots. It reroutes /api/*
# to the baked JSON and swallows writes, so api.js and the node code run
# unmodified. Image URLs can't go through here (they're <img src>, not fetch) —
# those are handled by the api.js override appended in write_api_shim().
SHIM_JS = """// static-shim.js — generated by export_static.py. Serves the baked
// /data/*.json in place of the Forge REST API. In the editor build, ForgeStore
// (IndexedDB) answers the stateful routes first; anything it declines falls
// through to the baked files. In the player build there is no store and every
// write is swallowed, so the published page can never be edited.
(function () {
  var ROUTES = __ROUTES__;
  var BASE = new URL('.', document.baseURI).pathname.replace(/\\/$/, '');
  var real = window.fetch.bind(window);
  var store = window.ForgeStore || null;

  function json(obj, status) {
    return new Response(JSON.stringify(obj), {
      status: status || 200, headers: { 'Content-Type': 'application/json' },
    });
  }

  window.fetch = function (input, init) {
    var url = typeof input === 'string' ? input
            : (input instanceof Request ? input.url : String(input));
    var u;
    try { u = new URL(url, location.href); } catch (e) { return real(input, init); }
    if (u.origin !== location.origin || u.pathname.indexOf('/api/') !== 0)
      return real(input, init);

    var method = ((init && init.method)
      || (input instanceof Request && input.method) || 'GET').toUpperCase();

    // the browser-local workspace owns projects, graphs and the gallery
    if (store) {
      return store.handleFetch(url, { method: method, body: init && init.body })
        .then(function (res) { return res || passThrough(u, method); })
        .catch(function (e) { return new Response(String(e.message || e), { status: 500 }); });
    }
    return Promise.resolve(passThrough(u, method));
  };

  function passThrough(u, method) {
    if (method !== 'GET') return json({ ok: true, static: true });

    var path = u.pathname;

    // images: /api/image?file=NAME -> /img/NAME
    if (path === '/api/image' || path === '/api/thumb') {
      var f = u.searchParams.get('file') || '';
      return real(BASE + '/img/' + encodeURIComponent(f));
    }
    // per-workflow schema: keyed file, 404 -> empty schema so the node still builds
    if (path === '/api/workflow/schema') {
      var key = u.searchParams.get('key') || '';
      return real(BASE + '/data/workflow-schemas/' + encodeURIComponent(key) + '.json')
        .then(function (r) { return r.ok ? r : json({ key: key, name: key, params: [], imageSlots: [] }); });
    }
    if (ROUTES[path]) return real(BASE + '/data/' + ROUTES[path]);
    return json({});
  }
})();
"""

# Appended to the copied api.js. `api` is a mutable object export, so overriding
# two methods here beats string-patching the original (which would drift).
API_OVERRIDE_PLAYER = """
// ── appended by export_static.py (player build) ──────────────────────────────
// Images are <img src>, not fetch, so the shim can't reroute them. Point them at
// the baked folder. The trailing `?v=` keeps `imageURL(f) + '&v=' + Date.now()`
// (nodes.js does this for depth/AI outputs) a valid URL.
const _staticImg = (file) =>
  new URL('img/' + encodeURIComponent(file), document.baseURI).pathname + '?v=';
api.imageURL = (_project, file) => _staticImg(file);
api.thumbURL = (_project, file) => _staticImg(file);
"""

API_OVERRIDE_EDITOR = """
// ── appended by export_static.py (editor build) ──────────────────────────────
// Hand the whole API over to the browser-local IndexedDB workspace. ForgeStore is
// installed by a classic script, so it is already on `window` by the time this
// module evaluates. Every method the store does not define (shaders, workflows)
// keeps its original fetch-based implementation and lands on the baked JSON.
Object.assign(api, window.ForgeStore.api);
"""


# ── helpers ──────────────────────────────────────────────────────────────────
def copy_tree(src: Path, dst: Path, patterns: List[str]) -> int:
    """Copy files matching any glob in `patterns`, preserving structure."""
    n = 0
    for pat in patterns:
        for p in sorted(src.glob(pat)):
            if not p.is_file():
                continue
            out = dst / p.relative_to(src)
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, out)
            n += 1
    return n


def referenced_images(graph: Dict[str, Any]) -> Set[str]:
    """Filenames the graph's nodes point at (Source `file`, depth/AI `output`)."""
    found: Set[str] = set()
    for node in graph.get("nodes") or []:
        props = node.get("properties") or {}
        for key in ("file", "output"):
            v = props.get(key)
            if isinstance(v, str) and v.lower().endswith(IMG_EXTS):
                found.add(Path(v).name)
    return found


MARKER = ".forge-static-export"     # proof a folder is ours before we ever delete it


def resolve_out(raw: str) -> Path:
    """Resolve --out, refusing anything that isn't safe to own outright.

    `Path('').resolve()` is the cwd, so an empty/blank --out would otherwise point
    the exporter at the repo itself — and --clean would then try to delete it.
    """
    if not raw or not raw.strip():
        raise SystemExit("--out is empty; give it a folder name (e.g. --out dist)")
    dist = Path(raw.strip()).resolve()

    if dist == ROOT or dist in ROOT.parents:
        raise SystemExit(f"refusing to use {dist}: that is the project itself "
                         "(or a parent of it)")
    if dist.parent == dist:
        raise SystemExit(f"refusing to use a filesystem root: {dist}")
    # never sit on top of a real source/data directory
    for name in ("forge_server", "web", "shaders", "mathnodes", "Workflows",
                 "projects", "venv", ".git", ".claude"):
        if dist == ROOT / name:
            raise SystemExit(f"refusing to use {dist}: that is the project's "
                             f"{name}/ directory")
    return dist


def prepare_out(dist: Path, clean: bool) -> None:
    """Make the output folder, only ever deleting a previous export of our own."""
    if dist.exists():
        if not dist.is_dir():
            raise SystemExit(f"{dist} exists and is not a directory")
        has_marker = (dist / MARKER).exists()
        if clean and not has_marker and any(dist.iterdir()):
            raise SystemExit(
                f"{dist} already has files and was not made by this script\n"
                f"(no {MARKER} marker). Refusing to delete it - pick an empty\n"
                f"folder, remove it yourself, or pass --no-clean to merge.")
        if clean and has_marker:
            shutil.rmtree(dist)
    dist.mkdir(parents=True, exist_ok=True)
    (dist / MARKER).write_text(
        "Generated by export_static.py. This file marks the folder as safe for\n"
        "the exporter to wipe on the next run; delete it to protect the folder.\n",
        encoding="utf-8")


def source_dir(settings: Dict[str, Any], kind: str) -> Path:
    """The configured shaders/mathnodes directory, falling back to the one beside
    this script. settings.json is tracked and carries absolute paths, so a fresh
    clone usually points at whatever machine last committed it."""
    getter = {"shaders": config.shaders_dir, "mathnodes": config.mathnodes_dir}[kind]
    try:
        d = getter(settings)
    except Exception:                                        # noqa: BLE001
        d = None
    if d is not None and d.exists():
        return d
    local = ROOT / kind
    print(f"  ! settings.json points {kind} at {d} which does not exist; "
          f"using {local}")
    return local


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


LITEGRAPH_TAG = '<script src="/web/graph/vendor/litegraph.js"></script>'


def inject_scripts(html: str, source_name: str, before: List[str],
                   after_modules: List[str]) -> str:
    """Put our classic scripts ahead of litegraph (so they run before the page's
    module scripts) and any ES-module extras at the very end of <body> (so they run
    after graphApp/play have populated RT)."""
    if LITEGRAPH_TAG not in html:
        raise SystemExit(f"{source_name} no longer loads litegraph.js the expected "
                         "way - update inject_scripts() in export_static.py")
    head = "".join(f'<script src="{s}"></script>\n  ' for s in before)
    html = html.replace(LITEGRAPH_TAG, head + LITEGRAPH_TAG)
    if after_modules:
        tail = "".join(f'  <script type="module" src="{s}"></script>\n'
                       for s in after_modules)
        if "</body>" not in html:
            raise SystemExit(f"{source_name} has no </body> to append to")
        html = html.replace("</body>", tail + "</body>")
    return html


def rewrite_root_refs(html: str) -> str:
    """Convert this build's own root-absolute asset tags (<script src="/web/…">,
    <link href="/js/…">) to plain RELATIVE references.

    The source HTML (web/graph/index.html, play.html) is authored for the desktop
    server, which mounts /web, /shaders, /mathnodes at domain root. This static
    build moves index.html/play.html to the build's own root while keeping web/ as
    a sibling — a fixed layout that never changes regardless of where the whole
    dist/ folder is later placed (domain root, or a subfolder of a bigger site, e.g.
    a portfolio). A relative reference resolves against wherever the CURRENT
    document is, so dropping the leading slash makes these tags self-relocating
    with no configuration, instead of needing a --base flag to get right.
    Scoped to our own namespaces only — never touches an author's own tags."""
    for ns in ("web", "js"):
        html = html.replace(f'src="/{ns}/', f'src="{ns}/')
        html = html.replace(f'href="/{ns}/', f'href="{ns}/')
    return html


def write_pages(dist: Path, mode: str) -> None:
    """index.html (+ play.html in editor builds), with the shim wired in."""
    graph_dir = ROOT / "web" / "graph"
    player = (graph_dir / "play.html").read_text(encoding="utf-8")

    if mode == "player":
        html = inject_scripts(player, "play.html", ["js/static-shim.js"], [])
        (dist / "index.html").write_text(rewrite_root_refs(html), encoding="utf-8")
        return

    editor = (graph_dir / "index.html").read_text(encoding="utf-8")
    # The desktop "classic" chain app isn't part of a static build. Point that
    # button at the player instead, which previews the user's own authored UI.
    # Matched loosely because the href has moved between / and /classic.
    editor, n = re.subn(
        r'<a class="btn" href="/(?:classic)?"[^>]*>classic[^<]*</a>',
        '<a class="btn" href="play.html" title="Preview your authored UI" '
        'target="_blank">preview ↗</a>', editor)
    if not n:
        print("  ! topbar 'classic' link not found; leaving links untouched")

    editor_html = inject_scripts(
        editor, "graph/index.html",
        ["js/forge-store.js", "js/static-shim.js"],
        ["web/graph/js/webeditor.js"])
    (dist / "index.html").write_text(rewrite_root_refs(editor_html), encoding="utf-8")

    player_html = inject_scripts(
        player, "play.html",
        ["js/forge-store.js", "js/static-shim.js"], [])
    (dist / "play.html").write_text(rewrite_root_refs(player_html), encoding="utf-8")


def write_api_shim(dist: Path, mode: str) -> None:
    src = (ROOT / "web" / "js" / "api.js").read_text(encoding="utf-8")
    override = API_OVERRIDE_PLAYER if mode == "player" else API_OVERRIDE_EDITOR
    out = dist / "web" / "js" / "api.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(src + override, encoding="utf-8")


# ── export ───────────────────────────────────────────────────────────────────
def export(mode: str, project: str, dist: Path, all_images: bool, clean: bool) -> None:
    settings = config.load_settings()
    graph: Dict[str, Any] = {}

    if mode == "player":
        pdir = config.project_dir(settings, project)
        if not pdir.exists():
            raise SystemExit(f"no such project: {project}  (try --list)")
        graph_path = pdir / "graph.json"
        if not graph_path.exists():
            raise SystemExit(f"{project} has no graph.json - nothing to publish. "
                             "Open it in the graph editor and save first.")
        graph = json.loads(graph_path.read_text(encoding="utf-8"))

    prepare_out(dist, clean)

    # Cache policy. The front-end is plain unhashed files (engine.js, graphApp.js…),
    # so without this a returning visitor keeps running an OLD deploy's JS against a
    # NEW deploy's HTML — exactly the stale-module bug that bites during testing.
    # `must-revalidate` lets the browser reuse a file only after checking it's current
    # (a cheap 304 when unchanged), so every redeploy is picked up immediately. Netlify
    # reads `_headers`; Cloudflare Pages reads it too.
    (dist / "_headers").write_text(
        "/*\n  Cache-Control: no-cache\n", encoding="utf-8")

    # 1. front-end
    n_web = copy_tree(ROOT / "web" / "graph", dist / "web" / "graph",
                      ["js/*.js", "vendor/*"])
    write_api_shim(dist, mode)
    write_pages(dist, mode)
    (dist / "js").mkdir(exist_ok=True)
    (dist / "js" / "static-shim.js").write_text(
        SHIM_JS.replace("__ROUTES__", json.dumps(ROUTE_FILES)), encoding="utf-8")
    if mode == "editor":
        # the browser-local workspace; must be a classic script, loaded first
        shutil.copy2(ROOT / "web" / "graph" / "js" / "forge-store.js",
                     dist / "js" / "forge-store.js")

    # 2. shaders + math nodes (sources the browser imports directly)
    n_sh = copy_tree(source_dir(settings, "shaders"), dist / "shaders",
                     ["*.js", "*.frag", "*.vert"])
    n_mn = copy_tree(source_dir(settings, "mathnodes"), dist / "mathnodes", ["*.js"])

    # 3. baked API responses — reuse the server's own builders so the shapes match
    data = dist / "data"
    write_json(data / "shaders.json", {"shaders": [
        {"key": p.stem,
         "js": f"/shaders/{p.name}",
         "frag": f"/shaders/{p.stem}.frag" if (dist / "shaders" / f"{p.stem}.frag").exists() else None,
         "vert": f"/shaders/{p.stem}.vert" if (dist / "shaders" / f"{p.stem}.vert").exists() else None}
        for p in sorted((dist / "shaders").glob("*.js")) if not p.stem.startswith("_")]})
    write_json(data / "mathnodes.json", {"mathnodes": [
        {"key": p.stem, "js": f"/mathnodes/{p.name}"}
        for p in sorted((dist / "mathnodes").glob("*.js")) if not p.stem.startswith("_")]})
    write_json(data / "comfy.json", {"ok": False, "reason": "static export"})

    wfs: List[Dict[str, Any]] = []
    if mode == "player":
        write_json(data / "graph.json", graph)
        write_json(data / "projects.json", {"current": project, "projects": [project]})
        write_json(data / "project.json", config.load_project(settings, project))
        write_json(data / "settings.json", {"current_project": project})

        # workflow list + schemas, so AI nodes still register and keep their shape
        try:
            wfs = workflows.scan(settings)
        except Exception as e:                               # noqa: BLE001
            print(f"  ! workflow scan failed ({e}); AI nodes will be missing")
        for wf in wfs:
            try:
                write_json(data / "workflow-schemas" / f"{wf['key']}.json",
                           workflows.build_schema(settings, wf["key"], None))
            except Exception as e:                           # noqa: BLE001
                print(f"  ! schema for {wf['key']} failed ({e})")
    # Editor builds ship no workflows: without ComfyUI the AI nodes can't run, and
    # not registering them keeps them out of the Add-node menu entirely.
    write_json(data / "workflows.json", {"workflows": wfs})

    # 4. images — player builds bake them; editor builds start empty (the visitor
    #    imports their own, straight into IndexedDB)
    shipped: List[Path] = []
    missing: List[str] = []
    bytes_ = 0
    if mode == "player":
        src_dir = config.project_paths(settings, project)["sourceimages"]
        pool = {p.name: p for p in src_dir.iterdir()
                if p.is_file() and p.suffix.lower() in IMG_EXTS} if src_dir.exists() else {}
        wanted = set(pool) if all_images else referenced_images(graph)

        img_dir = dist / "img"
        img_dir.mkdir(exist_ok=True)
        for name in sorted(wanted):
            p = pool.get(name)
            if not p:
                missing.append(name)
                continue
            shutil.copy2(p, img_dir / name)
            bytes_ += p.stat().st_size
            shipped.append(p)

        write_json(data / "gallery.json", {"images": [
            projects.entry(settings, project, p) for p in shipped]})

    # 5. a note for whoever deploys it
    if mode == "player":
        what = (f"Static export of Forge project '{project}' (player build).\n\n"
                "Read-only: saving, import, depth and AI Generate need the desktop app.\n")
    else:
        what = ("Static export of the Forge Graph EDITOR (web build).\n\n"
                "Each visitor gets a private workspace in their own browser (IndexedDB).\n"
                "Nothing is uploaded; there is no server and no shared state. Depth, AI\n"
                "and video nodes are disabled - they need ComfyUI/ffmpeg locally.\n\n"
                "index.html  the node editor\n"
                "play.html   the visitor's own authored UI, from their browser storage\n")
    (dist / "README.txt").write_text(
        what + "\nServe this folder at the ROOT of a domain (Cloudflare Pages, Netlify,\n"
        "S3+CloudFront). Asset paths are root-absolute, so a GitHub Pages project\n"
        "subpath (user.github.io/repo/) will NOT work without a custom domain.\n\n"
        "Local check:  python -m http.server 8000\n",
        encoding="utf-8")

    # ── report ──
    print(f"\n  {mode} build -> {dist}")
    if mode == "player":
        print(f"    project     {project}")
    print(f"    front-end   {n_web} files")
    print(f"    shaders     {n_sh} files")
    print(f"    math nodes  {n_mn} files")
    print(f"    workflows   {len(wfs)}" + ("" if wfs else "  (AI nodes disabled)"))
    if mode == "player":
        print(f"    images      {len(shipped)} ({bytes_ / 1_048_576:.1f} MB)"
              f"{'  [all]' if all_images else '  [referenced only]'}")
        if missing:
            print(f"    ! {len(missing)} referenced image(s) not in the project: "
                  + ", ".join(sorted(missing)[:5])
                  + (" ..." if len(missing) > 5 else ""))
    else:
        print("    storage     IndexedDB, per visitor")
    total = sum(p.stat().st_size for p in dist.rglob("*") if p.is_file())
    print(f"    total       {total / 1_048_576:.1f} MB\n")
    print(f"  test it:  cd {dist} && python -m http.server 8000\n")


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Bake Forge into a static site - either the editor (visitors "
                    "make their own graphs, stored in their browser) or a player "
                    "page frozen around one of your projects.")
    ap.add_argument("--mode", choices=("editor", "player"), default="editor",
                    help="editor: publish the node editor for anyone to use "
                         "(default). player: publish one project read-only.")
    ap.add_argument("--project", help="player mode only: which project to freeze "
                                      "(default: the current one)")
    ap.add_argument("--out", default="dist", help="output folder (default: dist)")
    ap.add_argument("--all-images", action="store_true",
                    help="player mode only: ship the whole gallery, not just the "
                         "images the graph uses")
    ap.add_argument("--no-clean", action="store_true",
                    help="merge into an existing output folder instead of replacing it")
    ap.add_argument("--list", action="store_true",
                    help="list projects and whether each has a graph to publish")
    args = ap.parse_args()

    settings = config.load_settings()
    if args.list:
        cur = settings.get("current_project")
        for name in config.list_projects(settings):
            has = (config.project_dir(settings, name) / "graph.json").exists()
            print(f"  {'*' if name == cur else ' '} {name:<24}"
                  f"{'graph.json' if has else '(no graph)'}")
        return

    if args.mode == "editor" and args.project:
        print("  ! --project is ignored in editor mode (visitors make their own)")

    export(args.mode,
           args.project or settings.get("current_project", "Untitled"),
           resolve_out(args.out), args.all_images, not args.no_clean)


if __name__ == "__main__":
    main()
